### ISSUE TITLE
Baronial Court Re-factor

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/adeptus-titanicus#104]
**File:** Household.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** The seneschal's banner is a baronial court and should be able to be equipped like a support banner for a battlegroup.

**Comment by capitaladot** [comment]
The best way to implement this is probably to make it a top level selection for a Household, 1 per Force, with links to the most customizable support-style Banners underneath.

**Comment by TrentBartlem** [comment]
makes sense, can also add the rule for upgrading a member to have the battle standard there too
