### ISSUE TITLE
high scion/seneschal validation bug

### ISSUE THREAD

**Issue by TrentBartlem** [BSData/adeptus-titanicus#106]
1. Make household list
2. Add 'show structure'
3. Add affiliation
4. Add 3 lances

roster errors (expected and actual):
* household must have 1 more selections from Seneschal (minimum 1) 
* household must have 1 more selections from High Scion (minimum 1)

5. Assign nobility=Seneschal to one lord scion

Roster errors (unexpected)
* household must have 1 more selections from High Scion (minimum 1)

(the roster passes validation with 1 seneschal and 1 high scion, but this is incorrect as seneschals and High Kings _replace_ high scions)

**Comment by capitaladot** [comment]
In process
