### ISSUE TITLE
Incorrect Princeps Seniores limitation

### ISSUE THREAD

**Issue by Ramrod-RMC** [BSData/adeptus-titanicus#110]
Currently, the roster creator is set up so that you can only have one Princeps Seniores per battlegroup, which is wrong. The 1.1 FAQ and Errata from February 2020 has the following question:

**Q. _Can you have more than one maniple in a Battlegroup? Does each maniple have a Princeps Senioris?_
A. Yes and yes. The minimum number of maniples is one, but there is no limit on the maximum number.**

So, one battlegroup, multiple maniples, each maniple with its own Princeps Seniores. This is my first time using Github, I hope I've put this in the correct place.

**Comment by capitaladot** [comment]
Thanks for the report and the FAQ find!
