### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by illuminati-dk** [BSData/adeptus-titanicus#127]
Hi,
I guess I'd better start working properly on GitHub and not through messages on discord.
For now i can do basic edits, hopefully I will be able to figure out the more complicated issues later

Cheers
/Illuminati
/Troels (Denmark)

**Comment by Deviltree** [comment]
You're in brother

**Comment by Deviltree** [comment]
@TrentBartlem can you add these guys? I don't seem to have the ability to add contributors.  We can probably drop some of the longer inactive folks if we need seats
