### ISSUE TITLE
Missing all legio specific items.

### ISSUE THREAD

**Issue by fjramsay** [BSData/adeptus-titanicus#14]
Missing:
Legio Specific Rules
Legio Specific Equipment
Legio Specific princeps Traits
Generic Princeps Traits

Two legios have this in the main rulebook, more are in Titandeath.

**Comment by fjramsay** [comment]
forgot to add:  
data file:  Adeptus Titanicus 2018 v6
Battlescribe 2.01.19  iphone version.

**Comment by capitaladot** [comment]
PR welcome. Get typing!

**Comment by fjramsay** [comment]
Is there a framework in place for these options?  I'll happily start filling them out if there is.  But I don't have experience making data files.

**Comment by capitaladot** [comment]
@fjramsay you would be very welcome to build it.

**Comment by capitaladot** [comment]
Implemented a ways back.
