### ISSUE TITLE
Doesn't support multiple Princeps Seniores

### ISSUE THREAD

**Issue by divercraig** [BSData/adeptus-titanicus#140]
**Describe the bug**
If you create a battlegroup and add 2 maniples to the group, each with it's own princeps seniores then you will see the following validation error:
![image](https://user-images.githubusercontent.com/3470279/133037623-a1a7e2f0-ecdc-4480-96dd-db3f164f2e5d.png)

**To Reproduce**
1. Create a new battle group
2. Add any maniple and set one titan to be Princeps Seniores
3. Add another maniple and set one titan to be Princeps Seniores of that maniple
3. Check the battlegroup validation
4. See error "Battlegroup v6 (Battlegroup) has 1 too many selections for Princeps Seniores (Maximum 1)

**Expected behavior**
The limit on Princeps Seniores should apply to the Maniple, not the Battlegroup

**Screenshots**

**Device and data (please complete the following information):**
 - OS: Mac OS
 - BattleScribe version 2.03.21
 - Release version Adeptus Titanicus 9.35

**Additional context**

**Comment by illuminati-dk** [comment]
Thanks for the very, very, nice error report - we'll add it to the list of issues
