### ISSUE TITLE
Warhound weapon characteristics have some mistakes

### ISSUE THREAD

**Issue by divercraig** [BSData/adeptus-titanicus#142]
**Describe the bug**
There are a number of weapon characteristics for a Warhound Titan which are not correct when compared with the details in the Latest Publication "Loyalist Legios". The following changes are required:

- Differentiate the Warhound and Reaver Turbo Laser Destructors as they have different characteristics
- Warhound Turbo Laser Destructor has a short range of 16", not the 18" of the Reaver variant
- Warhound Turbo Laser Destructor shouldn't have the Carapace trait
- Warhound Plasma Blast Gun Blast size isn't specified
- Warhound Vulcan Mega Bolter disable roll is set to "(+" instead of "9+"
- Ursus Claw and Natix Shock Lance are missing the Specialised trait
- Natrix Shock Lance is incorrectly marked as "shock" and "draining", when it should be "shock (draining)"

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a Warhound titan to a maniple
2. Add each weapon
3. Observe the characteristics of the weapons
4. Note that they do not match the publication

**Expected behaviour**
Warhound weapon characteristics match the loyalist legios publication

**Screenshots**
N/A

**Device and data (please complete the following information):**
 - OS: Mac OS
 - BattleScribe version: 2.03.21
 - Release version 9.3.7

**Additional context**
N/A

**Comment by Deviltree** [comment]
Cool looks like everything was good from the first Pull Request if you want to continue with this list

**Comment by divercraig** [comment]
I think I've got all the bugs in that first PR. Feel free to close this issue.

I'll try to do a review for other issues over the next few days.

**Comment by divercraig** [comment]
Warhound weapons are now fixed
