### ISSUE TITLE
Vulturum princept traits missing, Metallica princpt traits avaiable to everyone

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/adeptus-titanicus#146]
**File:** Adeptus Titanicus 2018.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Using Vulturum as my legio, under princept traits I get the generic book ones or the option to select legio Metallica ones

**Comment by zopha** [comment]
Yeap, getting Metallica Traits.

![image](https://user-images.githubusercontent.com/1666415/139749108-d73f5db0-7445-42a1-834c-b81855c2296d.png)

and Metallica is avaiable for other legio as well 
![image](https://user-images.githubusercontent.com/1666415/139749640-ae7a764c-167d-41af-b729-6543186d28eb.png)

But for the Vulturum traits.. They're missing from the princept. 

![image](https://user-images.githubusercontent.com/1666415/139749683-674ab594-cf6c-4076-bf6e-6d6071c299c4.png)

so two actions.

- [ ] Fix Metallica Traits appearing for other legios 
- [ ] Added Vulturum Princpet traits.

I have no idea what's causing the Metallica traits to appear, possiable a category set by mistake somewhere :(

**Comment by zopha** [comment]
Metallica traits where just not hidden. Will get Vulturum udpated when my book arrives or if someone else can get it done.
