### ISSUE TITLE
Reaver Vulcan Megabolters do not gain access to Static Rounds with Legio Interfector selected.

### ISSUE THREAD

**Issue by jimshacklock** [BSData/adeptus-titanicus#149]
Reavers should be able to take the Static Rounds upgrade for their carapace VMBs when selecting Legio Interfector as that titan's legio, however currently the option does not unlock.

**Comment by zopha** [comment]
I had a look on desktop and mobile and it's working for me. The rounds are on the Reaver entry rather then the VMB entry, under Legio Specific Wargear.

Desktop screenshot
![image](https://user-images.githubusercontent.com/1666415/139748604-ab188511-6a06-4c1e-a1ec-f5af0a009274.png)

**Comment by zopha** [comment]
Mobile screenshot.

![Screenshot_20211101_220912_net.battlescribe.mobile.rostereditor~2.jpg](https://user-images.githubusercontent.com/1666415/139748831-98b16cf8-ce2a-4bdf-becd-5fe17c21a8c7.jpg)

If it's not appearing for you can you try a full refresh of the data. If it still doesn't work can you provide some screenshots please.

**Comment by zopha** [comment]
Looking at the trator rules

> Each weapon must be upgraded separately

As the Reaver can have only one 1 VMB this implementation works but it doesn't on Warhounds when they can have two WH size VMB. Need to take a look and see if this would be better if it was a sub-select on both weapons. Would be useful if it's set up that way and we get other titans that can use the WH VMB.

**Comment by MoDLegion** [comment]
This is now fixed with #277, the upgrade is now a weapon specific option
