### ISSUE TITLE
Version 40 doesn't include Loyalist specific wargear options

### ISSUE THREAD

**Issue by divercraig** [BSData/adeptus-titanicus#163]
**Describe the bug**
Since updating to version 40 there are no Loyalist specific wargear option

**To Reproduce**
1. Create a new Battlegroup with a maniple and the loyalist allegiance
2. Edit a titan in the maniple
3. Not that there is no loyalist specific wargear option

**Expected behavior**
Loyalist titans should have access to loyalist specific wargear

**Screenshots**
![image](https://user-images.githubusercontent.com/3470279/141521331-9542e8ad-0890-49e6-afe5-3dc0e79f3877.png)

**Device and data (please complete the following information):**
 - OS: [e.g. iOS] Mac OS
 - BattleScribe version: v2.03.21.166
 - Release version [e.g. v1.2.3] v40

**Additional context**

**Comment by zopha** [comment]
Thanks, I've fixed that. I don't think it was touched last time but I can't be 100% sure, sometimes battlescribe introduces errors like these. The fix should be live tomorrow in version 41. Examples below.

Traitor selected - 
![image](https://user-images.githubusercontent.com/1666415/141529858-677f8b03-9b2a-49ab-b2cf-74a00cd2542c.png)


Loyalist selected - 
![image](https://user-images.githubusercontent.com/1666415/141529933-6ef642c5-83a1-4e41-b64c-c22aa4d08349.png)
