### ISSUE TITLE
Legio Interfector

### ISSUE THREAD

**Issue by zopha** [BSData/adeptus-titanicus#167]
Adding changes for Legio Interfector from the Traitors book.

Legio Traits
- [x] Creeping Madness

Legio Specific Stratagem
~~- [ ] Portents of Doom~~
~~- [ ] Tormented Machine Spirit~~

Legio Specific Wargear
- [ ] Static Rounds (see #149 )
  - [ ] Warhound
  - [ ] Reaver

Princep Traits
- [x] Dark Fanatic
- [x] Raving Madman
- [x] Hollowed Out

**Comment by zopha** [comment]
Argh, made commits on the master by mistake. Nearly all done, just need to sort out how to handle #149 and then this can be closed off.

**Comment by MoDLegion** [comment]
With #277 it resolves the last open task on this issue I suppose, so lets close this one as well!
