### ISSUE TITLE
Titandeath Supplement implementation

### ISSUE THREAD

**Issue by Corvinvs** [BSData/adeptus-titanicus#18]
Hello,

I made a local version of data file for Adeptus Titanicus with support Titandeath supplement. There are 4 new maniples and I also add Tempestus Legio specific wargear.

Could you please review attached file and merge it into master? It works fine for desktop version but unuseful for mobile.

Simply need to remove .zip extention. It was added for attachment only

[Adeptus Titanicus 2018.gstz.zip](https://github.com/BSData/adeptus-titanicus/files/3090265/Adeptus.Titanicus.2018.gstz.zip)

**Comment by capitaladot** [comment]
Thanks! Will review and get into a pull request.

**Comment by capitaladot** [comment]
@fjramsay took care of this in #20
