### ISSUE TITLE
Legio Tritonis

### ISSUE THREAD

**Issue by zopha** [BSData/adeptus-titanicus#186]
Adding changes for Legio Tritonis from the Traitors book.

Legio Traits
- [ ] Tide of Iron
  - [x] Description
  - [ ] Replace any mandatory Reavers with Warlords
- [x] Revel in Slaughter

Legio Specific Stratagem\
- [x] ~~Stygian Veil~~

Legio Specific Wargear
- [x] Radiative Warheads

Princep Traits
- [x] Tactical Genius
- [x] Lust for Vengeance
- [x] Leader of Arachnus

**Comment by GMTemplar** [comment]
Tide of Iron does not seem to be implemented at all.

**Comment by MoDLegion** [comment]
Tide of Iron will now be fixed as part of #212, when closing that I suppose this issue can be closed as well.
