### ISSUE TITLE
Knight Asterius addition

### ISSUE THREAD

**Issue by zopha** [BSData/adeptus-titanicus#189]
Issue to track implmentation of Mechanicum Acastus Knight Asterius

**Comment by zopha** [comment]
The changes that I can see

Points: 210

Autcannons removed and replaced with Twin Volkite Culverins.
Short 4"
Long 8"
Dice 2
Str 4
Traits: Voidbreaker (1)

Blessed Autosimulacra added (same rule as the Styrix, Magera and Atrapos although the first two don't have it in the roster and the Atrapos seems to be missing in the roster, not sure if it's in the files)

Artillery: If an Acastus Knight Banner is issued a First Fire or Split Fire orders during the Strategy phase, their BS is increased to 3+ until the End phase.

**Comment by MoDLegion** [comment]
We also need to adjust the banner size, it currently still contains more than 2, which is changed in the Errata and on the Asterius terminal itself. I'll try to get these changes in this weekend, then I think we have a nice package of updates to release with a bunch of Knight additions/fixes.

**Comment by MoDLegion** [comment]
Hmm, RAW the Acastus Knight Banner does not have the Blessed Autosimulacra. Only the Acastus Knight Asterius Banner has this rule (it is not added to the original command terminal in the errata). Technically the errata also doesn't update the weapon options of the Asterius on the original terminal. Blessed Autosimulacra also specifically targets ONLY Knight Asterius, so even if it was added to the original terminal, unless they change the wording, it won't count for Porphyrions.
