### ISSUE TITLE
Missing maniples rules in last update

### ISSUE THREAD

**Issue by Corvinvs** [BSData/adeptus-titanicus#21]
Greetings,

thanks a lot for update included maniples from Titandeath, Molech and WD. But you are missed maniple's specific rules for all new added maniples :( There are some rules only for initial two.

Are you going to add the rules for these maniples?
May I provide my local datafile or you prefer do it on your side?

Thanks.

**Comment by fjramsay** [comment]
Yea, I totally forgot to add the rules when I added the maniples.  my bad.  
if you have them done then either do a pull request or post the local data file here and I'll merge the changes into my tree and do a pull request.

**Comment by Corvinvs** [comment]
No problem. I attached my local .gstz file (the .zip added only for pass attach restriction)
[Adeptus Titanicus 2018.gstz.zip](https://github.com/BSData/adeptus-titanicus/files/3103583/Adeptus.Titanicus.2018.gstz.zip)

It contains rules for the Corsair, Dominus, Janissary, Lupercal and Regia maniples. 

I don't have the Doom of Molech book now, and cannot add correct rules for two maniples from this book.

**Comment by fjramsay** [comment]
Thanks, once I get Doom of Molech this weekend I'll add those rules and submit the patch.
