### ISSUE TITLE
Addition: Warlord-Sinister Psi-Titan for maniples

### ISSUE THREAD

**Issue by MoDLegion** [BSData/adeptus-titanicus#214]
The Warlord-Sinister Psi-Titan is not available for selection by Loyalist Legios in any maniple. It is present in the data but with no usages.

Would be an option for the following maniples (as these contain at least 1 Warlord):

- [ ] Axiom
- [ ] Dominus
- [ ] Extergimus
- [ ] Fortis
- [ ] Mandatum
- [ ] Myrmidon
- [ ] Perpetua
- [ ] Precept
- [ ] Regia

Care should be taken to continue on #212 to take Titan replacements into account for the following Legios, so a single Warlord isn't replaced twice.

- [ ] Legio Fortidus
- [ ] Legio Gryphonicus
- [ ] Legio Honorum

**Comment by zopha** [comment]
Aren't they a support titan that doesn’t join a Maniple so no Maniple swaps with it?

**Comment by MoDLegion** [comment]
Hmm you might be correct, the FW website states the following though:

"The Warlord-Sinister Psi-Titan is available to Loyalist Titan Legions in Adeptus Titanicus. One Warlord in a maniple may be replaced with this terrifying war engine."

I suppose the full rules are in the Shadow and Iron book.

**Comment by MoDLegion** [comment]
Ok nevermind, I managed to get the book and it indeed states "Psi-Titans cannot be included as part of a maniple or form
squadrons with any other Titan unless otherwise stated".
