### ISSUE TITLE
Dire Wolf Heavy Scout Titan - Unit addition

### ISSUE THREAD

**Issue by zopha** [BSData/adeptus-titanicus#217]
We have  a new scale 7 titan coming at some point.

The Warcom article is light on details except it's warhound size, can take a volcano cannon and two new weapons.

![34pFGRv0wUH5QTo1](https://user-images.githubusercontent.com/1666415/151334720-5dc65a4e-bbfc-4579-aaf2-fac476d5cd9f.jpg)

**Comment by MoDLegion** [comment]
Preorders are now up, reviews are in, all info can be found [here](https://spruesandbrews.com/2022/05/14/adeptus-titanicus-dire-wolf-heavy-scout-titan-unboxing/)
