### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by MoDLegion** [BSData/adeptus-titanicus#221]
### Reference contact

@zopha

### Your Discord

@Koetjeboe

### Additional information

I'm new to AT, but found the repo could use some attention and started some PR's to fix some issues. I put in a join request as suggested in #218, as this would make future collaboration on issues a bit easier.

**Comment by zopha** [comment]
Sorry for the pings @amis92 , could you take a look at this join request as well? Or is there a different route that I should request this?

Thanks!

**Comment by TrentBartlem** [comment]
Invite sent
