### ISSUE TITLE
Warmaster reactors

### ISSUE THREAD

**Issue by Slaughter-Melon** [BSData/adeptus-titanicus#229]
Warmaster reactors are supposed to be transferrable between the two warmaster chassis, currently locked to the cards they come with on the desktop release (android release seems to not have the iconoclast)

**Comment by MoDLegion** [comment]
@Slaughter-Melon can you provide some more detailed information on the BS version and OS version you are using? I'm having the same issue that the Iconoclast isn't showing up on mobile, but it works fine on desktop. For other people the mobile version does show the Iconoclast however and the data seems fine so we are having a hard time figuring out what is the problem.

**Comment by MoDLegion** [comment]
I managed to 'fix' the iconoclast issue for myself on mobile. It would seem BS is just bad at updating the data files. Mobile also has the option to delete the data before refreshing it, this fixed the issue for me.

**Comment by Slaughter-Melon** [comment]
I'm currently on V9.70 - 12th march, I've tried deleting and reinstalling on mobile and comes back with the same version

**Comment by MoDLegion** [comment]
Are you creating a Battlegroup or a Household list? I just noticed that the Iconoclast isn't actually properly added to the Household titans list.

Deleting the data from the app and deleting the app might be 2 separate things though, it's possible your phone caches the files downloaded by an app.
![Screenshot_20220313-140140-2](https://user-images.githubusercontent.com/97483529/158060800-ceb7c426-f24f-4b23-be2c-a7ee590f8770.jpg)

![Screenshot_20220313-140144](https://user-images.githubusercontent.com/97483529/158060776-2677495e-7639-4e52-8ff0-5f60f5088ae9.jpg)

**Comment by MoDLegion** [comment]
I have just released a hotfix (v.9.70.1) that adds the Warmaster Iconoclast to Household lists and updates the revision number of each of the  data files, hopefully that should resolve any update issues.

**Comment by MoDLegion** [comment]
On topic of the actually reported issue: I suppose that is the correct interpretation. Both the Warmaster and the Iconoclast command terminals have the 'Ancillary Reactor' slot and both kits come with 'Ancillary Reactor' cards, where both kits' weapon card are all specifically keyed to either the Warmaster or the Iconoclast.
