### ISSUE TITLE
Stratagem limit causing validation error

### ISSUE THREAD

**Issue by GMTemplar** [BSData/adeptus-titanicus#236]
**Describe the bug**
Stratagems cause a validation error even when the limit set is not exceeded.

**To Reproduce**
1. Setup a list of 1750 and limit the number of Stratagems Points to 5.
2. Add a maniple to the force.
3. Choose 5 points worth of stratagems.
4. See error "...has spent 1 Stratagem points too much from Stratagem (maximum 4 stratagem points)."

**Expected behavior**
Validation error should not occur when value of chosen stratagems does not exceed the limit set.

**Device and data (please complete the following information):**
 - Windows
 - BattleScribe version v2.03.21.166
 
 **Additional context**
Assuming opponent plays with single Legio rules, you will choose 5 or 6 stratagems to a 1750 list depending how you read the table in rulebook. In both cases this would currently cause a validation error when the limit is set to 5/6.

**Comment by MoDLegion** [comment]
Yeah the matched play SP limit is build into the 'Stratagem Points' category in in the data. That this is a thing is completely unclear in the app, and setting a custom SP limit will cause your issue when going past this build in limit. 

Reading the rule book, Stratagem Points can vary based on the mission in matched play, but will also potentially be different based on the # of maniples your opponent takes and a potential points difference. Even if that wasn't the case it is clearly very confusing and inter-plays badly with the custom SP limits you can set on a roster (e.g. it also doesn't work if you are building a list for open play and decide on any other number of SP).

For now the easiest approach would be to simply remove this build in limit. A better solution would be something similar to how the 40k repo does it, having a separate 'game configuration' section in which you select a battle size/game type etc which initialize the SP limit, possible an option to select # of maniples your opponent is using and a point difference.

**Comment by GMTemplar** [comment]
The SP limit should definitely be removed entirely. Pretty much everyone plays with Stratagem hand instead of point limit now as per Matched Play Guide. If someone really wants to use the old way of doing it, I'm sure they can handle counting to five. As it stands now, it doesn't work and it won't be missed.

**Comment by MoDLegion** [comment]
This issue has been solved as we replaced the stratagem section with the stratagem hand and a selector for the battlesize. If you still want a stratagem point on your list you can set it manually.
