### ISSUE TITLE
Wargear, Outflank + some typos

### ISSUE THREAD

**Issue by GMTemplar** [BSData/adeptus-titanicus#252]
The traitor wargear Corrosive Payload and Focused Capacitors are missing entirely and should be available to all Traitor Legios for their ordnance and maximal fire weapons respectively.

Legio Infernus wargear Clinging Phosphex says in summary text it can be bought for +20 points but currently in data files costs +15 points.

Stratagem Outflank is missing some unit options, Armigers and Moirax at least, which would make it cost 1 stratagem point.

Typos:
Stratagems: Blind Barage --> Blind Barrage
Iconoclast Warmaster Grav Imploder stat line: Shot --> Short

**Comment by MoDLegion** [comment]
I fixed these issues in v9.79.2!
