### ISSUE TITLE
Wrong Regia maniple composition

### ISSUE THREAD

**Issue by Corvinvs** [BSData/adeptus-titanicus#26]
The Regia Battleline manile has
Mandatory: two Warlords and one Warhound
Optional: two additional Warhounds

Current datafile has two Warlords as mandatory and allow add as many Warlords as you can and add only single Warhound as optional.

I can share my local datafile with fixed this and previous (related to the Lupercal maniple) issues if these issues are not in the current opened pull-request.

Thanks

**Comment by capitaladot** [comment]
I can't reproduce this in what is currently released. Please reply if you still see this after you get the latest release.
