### ISSUE TITLE
Legio Solaria Dire Wolf titans don't have the option of purchasing the Cameleoline Shrouding wargear

### ISSUE THREAD

**Issue by Coldstripe** [BSData/adeptus-titanicus#268]
**Describe the bug**
Legio Solaria Dire Wolves, despite being Scale 6 like Warhounds, can't purchase the Cameleoline Shrouding wargear - unlike regular Warhounds which can.

**To Reproduce**
1. Add a Dire Wolf titan to your list
2. Select Legio Solaria for that titan
3. Scroll down to "Leigo Specific Wargear" section
4. Section is blank, wargear unable to be purchased

**Expected behavior**

**Screenshots**
![image](https://github.com/BSData/adeptus-titanicus/assets/22808446/4231077e-90e7-4b50-a93e-91244097dc0d)
![image](https://github.com/BSData/adeptus-titanicus/assets/22808446/28c748f1-98cf-4ae0-aa1f-1224ff08f246)
![image](https://github.com/BSData/adeptus-titanicus/assets/22808446/33acad60-cea1-4f94-8ad5-a11e15f794e0)

**Device and data (please complete the following information):**
 - OS: Windows 11, Android
 - BattleScribe version 2.03.21
 - Release version 9.81.0

**Additional context**
N/A

**Comment by MoDLegion** [comment]
This is now fixed as of v9.81.1
