### ISSUE TITLE
Release Thread - 2023

### ISSUE THREAD

**Issue by zopha** [BSData/adeptus-titanicus#271]
Data Developers - Please use this issue to push new releases if doing so via comment.

Explainer
Create an issue comment that starts with /release on the first line.
Second (non-empty) line will be used as a release title/name.
All following lines will be interpreted as a release description/body.
Description (even if empty) will always be appended with a comparison link to the previous release, unless there is no previous release.
How to
Add a comment with one of the following to push a release:

For a standard release:
given latest release v2.2.2, will create a release v2.2.3 (increases patch)

/release

This is title of v2.2.3

For a Chapter Approved/Big FAQ initial releases (game-wide updates):
given latest release v2.2.2, will create a release v2.3.0 (increases minor, resets patch)

/release bump=minor

This is title of v2.3.0

For a new game edition:
given latest release v2.2.2, will create a release v3.0.0 (increases major, resets minor and patch)

/release bump=major

This is title of v3.0.0

**Comment by zopha** [comment]
/release

Sinister beamer (added conversion beamer to psi-titan)

**Comment by zopha** [comment]
/release

Sinister beamer (added conversion beamer to psi-titan)

**Comment by zopha** [comment]
/release

Added Legio Metallica strat.

**Comment by MoDLegion** [comment]
/release bump=minor

Added LI Warhound weapons

**Comment by MoDLegion** [comment]
/release 

Fixed Legio Gryphonicus not allowing optional Warlords/Warhounds to be replaced with Reavers.

**Comment by MoDLegion** [comment]
/release bump=minor

Added conversion beam dissipators for dire wolfs

**Comment by MoDLegion** [comment]
/release bump=minor

Added a battle size selector and changed the 'stratagem' category into a 'stratagem hand' according to the matched play guide. Stratagem point limits are now to be set manually for a roster.

**Comment by MoDLegion** [comment]
/release bump=minor

Mordaxis fixes by @nygellyndley

**Comment by TrentBartlem** [comment]
/release

Wargear fixes by @BoaPi

**Comment by MoDLegion** [comment]
/release bump=minor

Switch to NRDataEditor by @BoaPi 
Princeps Seniores fix by @MoDLegion

**Comment by MoDLegion** [comment]
/release

Updated readme with instructions for legacy BS users

**Comment by jorisvangestel** [comment]
/release bump=minor

This repository is now no longer actively maintained
