### ISSUE TITLE
[Join Request] I want to commit fixes to the Titanicus repo

### ISSUE THREAD

**Issue by nygellyndley** [BSData/adeptus-titanicus#278]
I already have a PR in here : https://github.com/BSData/adeptus-titanicus/pull/277
and have a follow up PR to add the new Warhound weapons, but looking at the docs it's advised I request write access so am doing so via this raised issue.

Thanks

**Comment by Mad-Spy** [comment]
@Deviltree @TrentBartlem  Please either action this request or respond to say that you are no longer wanting to be admins for this repo.
