### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by wdh-dev** [BSData/adeptus-titanicus#293]
The Adeptus Titanicus repo is flagged as deprecated due to a fork for new features for new recruit. Lots of people still use the repository in battlescribe however and I want to make sure that the new released units are added.

**Comment by Mad-Spy** [comment]
I'd suggest talking to the current AT authors on Discord first. We are all moving away from Battlescribe due to its status as abandonware.

**Comment by wdh-dev** [comment]
Yes, that was always my itention and I've posted on the discord. Thanks.
