### ISSUE TITLE
Options for Legion Specific wargear are not showing up after Legion is chosen, e.g. Hunting Auspexs for Tigers Eyes

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/adeptus-titanicus#31]
**File:** Battlegroup.catz

**BattleScribe version:** 2.02.04

**Platform:** Windows

**Dropbox:** No

**Description:** Options for Legion Specific wargear are not showing up after Legion is chosen, e.g. Hunting Auspexs for Tigers Eyes

**Comment by morvael** [comment]
Duplicate of [issue 14](https://github.com/BSData/adeptus-titanicus/issues/14).
