### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by bjUndergound** [BSData/adeptus-titanicus#38]
i'd like to help by adding the Legions in the Shadow and Iron update and to add more legio specific wargear in a similar way to the Legio Griphonicus.

I've been using git for a long while, so am comfortable with the processes discussed in your tutorials. I have had a little play around with the data editor tool and I'm pretty comfortable with that as well!

I look forward to getting involved!

**Comment by capitaladot** [comment]
@amis92

**Comment by amis92** [comment]
@capitaladot you're admin here as well, feel free to exercise your role :)

Hint: https://github.com/BSData/adeptus-titanicus/settings/access

❤, Amis
