### ISSUE TITLE
Stat tracking options 

### ISSUE THREAD

**Issue by MountyChris** [BSData/adeptus-titanicus#42]
Is there any way to turn off/ hide the stat tracking options? 
Trying to export a roster to text and it makes it unwieldy. 
Thanks

**Comment by bjUndergound** [comment]
i think it should be possible to toggle these with some adjustment. This is not an insignificant change. A note will be added here with further updates.

**Comment by Dread-AT18** [comment]
I'd second this. I currently delete the list of locations as they bulk out the lists functionality. 👍

**Comment by bjUndergound** [comment]
I've made the changes, they'll need to be reviewed but assuming that's all good we'll get them pushed in the next update

**Comment by bjUndergound** [comment]
@MountyChris and @Dread-AT18, this issue seems to have reemerged after recent changes.

I'll have another look at this to see whats happened
