### ISSUE TITLE
Titans of legend and custom legio data 

### ISSUE THREAD

**Issue by MountyChris** [BSData/adeptus-titanicus#45]
As a hopefully useful resource, I've collated all the parameters  needed for creating  a custom legio.  I've also added the details for all the titans of legend. 

https://docs.google.com/spreadsheets/d/1_dhZp2KRfwITbs4y8IJdvYonBaeW0fsy7NV122bptLY/edit?usp=drivesdk

Cheers

**Comment by capitaladot** [comment]
Thanks!

**Comment by MountyChris** [comment]
Imgur of the legendary titans

https://imgur.com/a/AX1nPcn

**Comment by bjUndergound** [comment]
nice one thanks!
