### ISSUE TITLE
Possible Interfector and Mordaxis typos?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/adeptus-titanicus#47]
**File:** Adeptus Titanicus 2018.gstz

**BattleScribe version:** 2.03.13

**Platform:** Windows

**Dropbox:** No

**Description:** Legio Interfector Static Rounds +20 points instead of +15 (description bubble says 15 but points cost is 20)
Legio Mordaxis: shouldn't the toxin nodes upgrade be separate, just for the whole titan, same as Interfector and Infernus?

**Comment by Alex-Abernethy** [comment]
This can be closed. 
Legio Mordaxis rules are price per upgraded gun.
Static rounds are 15pts when you upgrade a model (checked data file and tested with a Warhound and Reaver in Android app).
