### ISSUE TITLE
Legio Swap Issues

### ISSUE THREAD

**Issue by mooftak** [BSData/adeptus-titanicus#51]
When making a legio fortidus axiom maniple  you should be able to swap out any mandatory titan for a different one. No swap is currently possible.

When creating a legio krytos myrmidon maniple you should be able to swap the mandatory reaver for a warlord and still be able to add both a warlord and a reaver as optional components. Only the warlord is an option and you get an error that you are not allowed to have a reaver.

**Comment by Deviltree** [comment]
Venator and Tritonis swaps as well

**Comment by capitaladot** [comment]
Reading over this I feel like it is probably the tip of the feature gap iceburg. I have added what is articulated in the mentioned maniples, but suspect there is probably more missing. A fully written out matrix of the swaps would help.
