### ISSUE TITLE
Defence of Ryza

### ISSUE THREAD

**Issue by RandallBurt** [BSData/adeptus-titanicus#52]
Defense of Ryza released. I have the data updated locally and can submit a PR unless someone else is already working on it.

**Comment by capitaladot** [comment]
Submission welcome!

**Comment by RandallBurt** [comment]
Cool! I just realized that I've made these changes using the wrong data file, so I should have a PR in a day or so.

**Comment by RandallBurt** [comment]
Still looking for someone with commit powers to take a look at the associated PR.
