### ISSUE TITLE
Add Venerable Machine Spirit Strat

### ISSUE THREAD

**Issue by TrentBartlem** [BSData/adeptus-titanicus#60]
source: [WD458](https://www.warhammer-community.com/2020/11/09/white-dwarf-preview-issue-458/)

cost: 2

Can probably read the text from places like [here](https://www.ebay.com/itm/Adeptus-Titanicus-Venerable-Machine-Spirit-Stratagem-Card-Promo-/383856125840)

**Comment by TrentBartlem** [comment]
The selectionEntry has been created, but it's not showing up. I think there needs to be an entrylink to the Strategy categoryEntry for it to turn up.

**Comment by capitaladot** [comment]
I added the link in Strategy.
