### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Alex-Abernethy** [BSData/adeptus-titanicus#62]
Hey
I'd like to help out with the Adeptus Titancus repo. Recently started playing and I've been using BS for my lists. I would like to help with the minor bugs to get my feet under me and then help with things like adding the mechanicum knights.
Regards
Alex

**Comment by TrentBartlem** [comment]
No need for special permissions - just fork the repo into your own copy, make changes and submit a pull request back to us!
