### ISSUE TITLE
Add support for Knight Households

### ISSUE THREAD

**Issue by TrentBartlem** [BSData/adeptus-titanicus#66]
From issue #49 

> is it possible to make a Knighly Househould roaster for knight lists and so get available for the knight stratagems similar to the legion specific ones?

- [x] Basic scaffold in Household.cat from the GST
- [x] Movement of most the Battlegroup Maniples into Battlegroup.cat  
- [x] Nobility rules
- [x] Knight Houses; this is started  
  - [x] Doom of Molech
  - [x] Shadow and Iron
  - [x] Defense of Ryza
  - [x] Crucible of Retribution
- [x] Knightly Qualities; this is started but I am in show/hide hell with the first I have added, House Divine's Knightly Qualities
- [x] Knight Strategems 
- [x] more refactoring of Battlegroup stuff from the GST into Battlegroup.cat (where possible; some stuff has to stay, I think?)
- [x]  work out constraints to require identical Knight equipment for Lance Banners.

**Comment by capitaladot** [comment]
I must have closed this by mistake.

**Comment by TrentBartlem** [comment]
👍

**Comment by capitaladot** [comment]
@TrentBartlem et al: love to have your thoughts on how crucial the "all banners equipped alike" enforcement is.

**Comment by TrentBartlem** [comment]
I'm perfectly fine with multiple pull requests to complete this feature, so don't let it be a show stopper.

As far as the importance goes, it's a crucial constraint that everyone who runs entire houses chafes under and will expect support for

**Comment by cartag** [comment]
@capitaladot if it's a matter of "how in the hell am I going to implement this," if the Banners are each SSEs, you could set them Max 0 in Roster for all of them but one, provided that one is set on a checkbox/radio button. I don't know exactly how they're set up, but do they all have to match one certain unit, or just all have to be the same?

**Comment by TrentBartlem** [comment]
> With the exception of your Seneschal’s Banner, each Knight in the same Banner must be equipped identically.

I think freeblade Banners also ignore this rule. Perhaps you can add a separate type of banner group for the two types?

**Comment by capitaladot** [comment]
My mod-god powers are out of control @TrentBartlem; I thought I was editing my own response and I accidentally edited what you wrote. lol
