### ISSUE TITLE
Battlegroups completely gone

### ISSUE THREAD

**Issue by TrentBartlem** [BSData/adeptus-titanicus#78]
V22, release 7.0

> Bug: the only option is now to create "Battlegroup v3"  at which point the only options listed is "Uncategorised, show structure"
> No titans, knights or anything else possible.
> So for me it's coming up as entirely broken.

**Comment by Deviltree** [comment]
We may need to go back a build further, it's definitely broken.  I have a call in just a few minutes but I'll see if I can fix it.

**Comment by capitaladot** [comment]
Fixed in latest, re-tested on both Android and Desktop. Think I neglected to upversion CATs and GST in sync, which works on desktop with only Dropbox mounted files, but goes to hell on mobile with a local cache version intermittently updated from Appspot and/or Dropbox.
