### ISSUE TITLE
Questoris support banner

### ISSUE THREAD

**Issue by Darkenwood** [BSData/adeptus-titanicus#8]
there is a minor bug turned up when selecting the Questoris support banner, the amount of knight hulls required is increasing when selecting a knight hull instead of decreasing.

**Comment by capitaladot** [comment]
This was an anon pull request I reviewed but did not test (big hassle
because it wasn't a branch of the project).

I will take a look at it soon. Are the Questoris hulls even out yet?

**Comment by Darkenwood** [comment]
the Questoris hull is the standard knight option, I can upload bug fix in about 20min if required

**Comment by capitaladot** [comment]
Derp, I was thinking Cerastus.

Pull/join requests welcome!

**Comment by Darkenwood** [comment]
sorry it took longer to get my head around using the git hub software
