### ISSUE TITLE
Princeps Senores Traits

### ISSUE THREAD

**Issue by Deviltree** [BSData/adeptus-titanicus#85]
Would like to add a system for Princeps Senores (just like Warlords in the 40k) 

- [x] Ability to designate a titan a Princeps Senores 
- [x] Selecting PS will give you the rulebook PS traits plus legio specific PS traits
- [x] AT
- [x] DoR
- [x] TD
- [x] DoM
- [x] CoR
- [x] SaI

**Comment by capitaladot** [comment]
I knocked out the stratagem category merge thing, but would you want to jump in on filling in Seniores Personal traits, @Deviltree?

**Comment by capitaladot** [comment]
Rolling on this.
