### ISSUE TITLE
Tweak Strategem structure

### ISSUE THREAD

**Issue by TrentBartlem** [BSData/adeptus-titanicus#86]
At present, there's separate top-level entries for 'Stratagem' vs 'Legio Specific Stratagem'.

It would be better if they were merged into a single top-level entry, and each legio-specific stratagem is hidden unless there are at least one maniple with the matching legio.

**Comment by Deviltree** [comment]
That shouldn't be to hard to put in place, I'll see what I can do

**Comment by capitaladot** [comment]
I think that we should probably hide these based on which Legios are in your Roster. The list is pretty unwieldy right now.

**Comment by TrentBartlem** [comment]
There's already strats that disappear if you aren't traitor or loyalist etc, so there's precedent.
