### ISSUE TITLE
Base Knightly Qualities not radio box but house-specific are?

### ISSUE THREAD

**Issue by TrentBartlem** [BSData/adeptus-titanicus#92]
see https://i.imgur.com/MFFwWHZ.png

**Comment by capitaladot** [comment]
I think it is doing this because I nested the House specific Qualities inside the generic Qualities. It is possible moving around the constraints and nesting might avoid this, but I'm not sure.

**Comment by TrentBartlem** [comment]
tbh i prefer the radio buttons ha

**Comment by capitaladot** [comment]
I agree, it should be radio buttons. BS UI is quirky and does things under weird combinations of related choices.

**Comment by TrentBartlem** [comment]
princeps traits seem to both be radio boxes so idk what the difference is?
