### ISSUE TITLE
High Scion is required, one per Lance Banner. This is not yet enforced.

### ISSUE THREAD

**Issue by capitaladot** [BSData/adeptus-titanicus#94]
High Scion is required, one per Lance. This is not yet enforced.

**Comment by TrentBartlem** [comment]
some lance banners can have 2+ lord scions (e.g. cerastus lancers)

**Comment by capitaladot** [comment]
> some lance banners can have 2+ lord scions (e.g. cerastus lancers)

If I understand you correctly, are you suggesting that a Cerastus Lancer Banner or Model could have both a Seneschal and a High Scion? As I read the text on DoM p38, it appears that Seneschal, Lord Scion, and High Scion are mutually exclusive designations, so it is a case of promoting one Lord Scion per Lance to High Scion, and one other High Scion per Household to Seneschal? 

> 
> One Lance within the force must be designated as belonging to
> the Seneschal, rather than a Lord Scion or High Scion.
> • One Banner within this Lance must be designated as
> containing the Seneschal, in the same way as a Banner within
> another Lance would be designated as containing a High Scion.

**Comment by TrentBartlem** [comment]
no, it's currently possible to add multiple scions to a cerastus lancer household banner

**Comment by capitaladot** [comment]
Is this a Lancer special rule I have missed, or a bug? 
I can't replicate being able to add multiple Cerastus Knight Lord Scion models in the Lance Cerastus Banner in the Household Force (and barring some weird proviso I missed, that would be a bug).

**Comment by TrentBartlem** [comment]
In a household I can add up to 3 total lancers and unlimited scions on mobile without validation errors
