### ISSUE TITLE
Audit legio-specific strats work correctly

### ISSUE THREAD

**Issue by TrentBartlem** [BSData/adeptus-titanicus#99]
- [x] astraman no strats
- [x] atarus has a damicium strat as well
- [x] audax shows astorum strats instead
~~- [ ] crucis no strats~~ none published I could find
- [x] damicium no strats (but linked elsewhere)
~~- [ ] gryphonicus no strats~~ none published I could find
- [x] honorum shows astorum strats instead
- [x] ignatum no strats
- [x] kulisaetai no strats
- [x] laniaskari no strats
- [x] mordaxis also shows astorum
- [x] oberon also shows astorum
- [x] praesagius also shows astorum
- [x] tempestus also shows vulcanum
- [x] tritonis no strats
~~- [ ] venator no strats~~ none published I could find
- [x] vulcanum no strats (but linked elsewhere)

**Comment by capitaladot** [comment]
Appears that the Legios shared picker did not have categories assigned as appropriate to the selections within that control the show/hide behavior; show hide modifiers seem to be clean.
